const users = {
  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  SOCIAL_REQUEST: 'SOCIAL_REQUEST',
  SOCIAL_SUCCESS: 'SOCIAL_SUCCESS',
  SOCIAL_FAILURE: 'SOCIAL_FAILURE',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',
  EDIT_USER_REQUEST: 'EDIT_USER_REQUEST',
  EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
  EDIT_USER_FAILURE: 'EDIT_USER_FAILURE',
  DELETE_USER_REQUEST: 'DELETE_USER_REQUEST',
  DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
  DELETE_USER_FAILURE: 'DELETE_USER_FAILURE',
};

const categories = {
  LOAD_CATEGORIES_REQUEST: 'LOAD_CATEGORIES_REQUEST',
  LOAD_CATEGORIES_SUCCESS: 'LOAD_CATEGORIES_SUCCESS',
  LOAD_CATEGORIES_FAILURE: 'LOAD_CATEGORIES_FAILURE',
  LOAD_CATEGORY_REQUEST: 'LOAD_CATEGORY_REQUEST',
  LOAD_CATEGORY_SUCCESS: 'LOAD_CATEGORY_SUCCESS',
  LOAD_CATEGORY_FAILURE: 'LOAD_CATEGORY_FAILURE',
};

const polls = {
  LOAD_POLLS_REQUEST: 'LOAD_POLLS_REQUEST',
  LOAD_POLLS_SUCCESS: 'LOAD_POLLS_SUCCESS',
  LOAD_POLLS_FAILURE: 'LOAD_POLLS_FAILURE',
  LOAD_POLL_REQUEST: 'LOAD_POLL_REQUEST',
  LOAD_POLL_SUCCESS: 'LOAD_POLL_SUCCESS',
  LOAD_POLL_FAILURE: 'LOAD_POLL_FAILURE',
  LOAD_CATEGORIES_REQUEST: 'LOAD_CATEGORIES_REQUEST',
  LOAD_CATEGORIES_SUCCESS: 'LOAD_CATEGORIES_SUCCESS',
  LOAD_CATEGORIES_FAILURE: 'LOAD_CATEGORIES_FAILURE',
  LOAD_CATEGORY_REQUEST: 'LOAD_CATEGORY_REQUEST',
  LOAD_CATEGORY_SUCCESS: 'LOAD_CATEGORY_SUCCESS',
  LOAD_CATEGORY_FAILURE: 'LOAD_CATEGORY_FAILURE',
  ADD_POLL_REQUEST: 'ADD_POLL_REQUEST',
  ADD_POLL_SUCCESS: 'ADD_POLL_SUCCESS',
  ADD_POLL_FAILURE: 'ADD_POLL_FAILURE',
  EDIT_POLL_REQUEST: 'EDIT_POLL_REQUEST',
  EDIT_POLL_SUCCESS: 'EDIT_POLL_SUCCESS',
  EDIT_POLL_FAILURE: 'EDIT_POLL_FAILURE',
  DELETE_POLL_REQUEST: 'DELETE_POLL_REQUEST',
  DELETE_POLL_SUCCESS: 'DELETE_POLL_SUCCESS',
  DELETE_POLL_FAILURE: 'DELETE_POLL_FAILURE',
  VOTE_REQUEST: 'VOTE_REQUEST',
  VOTE_SUCCESS: 'VOTE_SUCCESS',
  VOTE_FAILURE: 'VOTE_FAILURE',
};

const store = {
  users,
  categories,
  polls,
};

export default store;
